### ISSUE TITLE
Uncaught TypeError: Object [object Object] has no method 'setLine' 

### ISSUE THREAD

**Issue by LevyGuy** [wanggit/brackets-add-comment#2]
I get an error when trying to add comments.
The CodeMirror object doesn't have "setLine" method.
on comment.js line:139
see attached image
![untitled](https://cloud.githubusercontent.com/assets/1586416/2927454/ab8ad9e4-d76c-11e3-96f9-67150c64a020.png)

**Comment by wanggit** [comment]
fixed
